apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sock-shop-front
  namespace: sock-shop
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: sock-shop-front.CLUSTER_SPECIFIC_DNS_ZONE
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-end
            port:
              number: 8079